### ISSUE TITLE
弱弱的问一下大佬，db.conf 报错

### ISSUE THREAD

**Issue by sinianzhiren** [xpioneer/koa-graphql-typescript#3]
Cannot find module '../../../conf/db.conf'，请问db.conf是自己数据库的配置项吗

**Comment by AddJunZ** [comment]
> Cannot find module '../../../conf/db.conf'，请问db.conf是自己数据库的配置项吗

这个文件被.gitignore省略掉了，确实是数据库配置

**Comment by xpioneer** [comment]
额，太久远了。。就是数据库的配置...因为我之前有发到线上的，所以这个被忽略了。
